name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable]
        jdk: ["25.0.1"]
        jdk_distribution: ["oracle"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Set up Java (${{ matrix.jdk_distribution }} ${{ matrix.jdk }})
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.jdk_distribution }}
          java-version: ${{ matrix.jdk }}

      - name: Cache compiled fixtures
        id: cache-fixtures
        uses: actions/cache@v4
        with:
          path: target/test-classes
          key: >
            ${{ runner.os }}-jdk-${{ matrix.jdk }}-${{ matrix.jdk_distribution }}-fixtures-
            ${{ hashFiles('javap/tests', 'javap/build.rs', 'vm/tests', 'vm/build.rs')}}

      - name: Check formatting
        run: cargo fmt --all -- --check

      # TODO: re-enable clippy once warnings are resolved
      # - name: Clippy
      #   env: { RUSTFLAGS: -Dwarnings }
      #   run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --verbose --locked

      - name: Run tests
        run: cargo test --verbose --locked
